### ISSUE TITLE
Duda ejercicios opcionales

### ISSUE THREAD

**Issue by mpenalverm** [mpenalverm/decont#1]
Buenos días, 
Estoy intentando hacer los ejercicios opcionales y me ha surgido una duda: ¿existe alguna forma de valorar si los ficheros de las url ya están descargados si usamos la opción wget one-liner? En el resto de los comandos uso un if dentro de los bucles, pero si lo hago en este sería parecido a usar el scripts/download.sh en vez del one-liner.
Un saludo,

**Comment by tdido** [comment]
Hola Marcos. Buscá en el help (`man wget`) la palabra "clobber".

**Comment by mpenalverm** [comment]
Muchas gracias! Ya me funciona.
