### ISSUE TITLE
Nueva duda

### ISSUE THREAD

**Issue by mpenalverm** [mpenalverm/decont#2]
Creo que ya está completo el script, con los dos ejercicios opcionales. Lo único, para los comandos de Star he considerado que ya se había ejecutado si se creaba un fichero SAindex (para el index) o un fichero Aligned.out.sam (para el alineamiento) suponiendo que si se han generado es porque ha funcionado el comando, pero no se si esos ficheros se generan siempre o dependiendo de si se producen alineamientos o no, 
Un saludo

**Comment by tdido** [comment]
Está perfecto, podés asumir que esos archivos indican que se ejecutó cada software correctamente. Como sospechás, puede haber casos en los cuales no sea un chequeo suficiente, pero a los efectos de este ejercicio va bien (y, te aseguro, te vas a encontrar chequeos así en muchos casos reales...).

**Comment by mpenalverm** [comment]
Estupendo, muchas gracias! ¿entonces considero el ejercicio ya completo?

**Comment by tdido** [comment]
En cuanto me digas lo reviso.

**Comment by mpenalverm** [comment]
De acuerdo, ya está listo para revisar

**Comment by tdido** [comment]
La solución está perfecta, Marcos, muy buen trabajo.

Sólo como curiosidad, te comento que existe el argumento `-i` de wget que toma un archivo con un listado de URLs y las descarga. La única situación en la que puedo imaginarme que tu solución no funcionara sería si el listado de archivos fuera muy largo, y entonces se excediera el límite de longitud de comandos bash. Pero en ese caso se haría probablemente una descarga paralela.

Como te decía, sólo para que conozcas la opción. Tu solución es correcta.
